import axios from 'axios';
import { useState, useEffect } from 'react';
import React from 'react';
import {
  CCard,
  CCardBody,
  CCol,
  CRow,
  CButton,
  CTable,
  CTableHead,
  CTableRow,
  CTableHeaderCell,
  CTableBody,
  CTableDataCell,
  CFormFloating,
  CFormInput,
  CFormLabel,
  CModal,
  CModalHeader,
  CModalBody,
  CModalTitle,
  CModalFooter,
  CAlert,
  CNav,
  CNavLink
} from '@coreui/react';

const Products = () => {
  const [arrProducts, setArrProducts] = useState([]); //data
  const [visible, setVisible] = useState(false) //modalInsertar
  const [visibleEditar, setVisibleEditar] = useState(false) //modalEditar
  const [visibleEliminar, setVisibleEliminar] = useState(false) //modalEditar
  const [exito, setExito] = useState(false)
  const [exitoEditar, setExitoEditar] = useState(false)
  const [exitoEliminar, setExitoEliminar] = useState(false)
  const [newProduct, setNewProduct] = useState({ //gestorSeleccionado
    idProduct: 0,
    name: '',
    category: '',
    unitPrice: 0.0,
    active: 1
  })
  const url = 'http://localhost:5000/products/';

  useEffect ( () => {
    pGet();
  }, [])

  //Cambio en el input
  const handleChange = (e) => {
    const {name, value} = e.target
    setNewProduct({ ...newProduct, [name]: value })
  }

  //Peticiones
  const pGet = async () => {
    await axios.get(url)
    .then (response => {
      setArrProducts(response.data)
    })
    .catch (error => {
      console.log(error)
    })
  }

  const pPost = async () => {
    delete newProduct.idProduct; //generated by db
    newProduct.unitPrice = parseFloat(newProduct.unitPrice)
    await axios.post(url, newProduct) //url and body
    .then (response => {
      setVisible(false)
      setExito(true)
    })
    .catch (error => {
      console.log(error)
    })
  }

  const pPut = async () => {
    newProduct.unitPrice = parseFloat(newProduct.unitPrice)
    await axios.put(url + newProduct.idProduct, newProduct) //url and body
    .then (response => {
      var respuesta = response.data
      var dataAuxiliar = arrProducts
      
      dataAuxiliar.map(product => {
        if (product.id === newProduct.id){
          product.name = respuesta.name
          product.category = respuesta.category
          product.unitPrice = respuesta.unitPrice
          product.active = respuesta.active
        }
      })
      setVisibleEditar(false)
      setExitoEditar(true)
    })
    .catch (error => {
      console.log(error)
    })
  }

  const pDelete = async () => {
    await axios.delete(url + newProduct.idProduct)
    .then (response => {
      setArrProducts(arrProducts.filter(product => product.id !== response.data))
      setVisibleEliminar(false)
      setExitoEliminar(true)
    })
    .catch (error => {
      console.log(error)
    })
  }

  const onSelectedProduct = (product, action) => {
    setNewProduct(product)
    if (action === 'Edit') setVisibleEditar(true)
    else setVisibleEliminar(true)
  }

  useEffect ( () => { 
    pGet();
  }, [visibleEliminar])

  useEffect ( () => { 
    pGet();
  }, [visibleEditar])

  useEffect ( () => { 
    pGet();
  }, [visible])

  return (
    <CRow>
      <CCol>
        <CCard className='mb-3'>
          <CCardBody>
            <CNav component="nav" variant="pills" className="flex-column flex-sm-row">
              <CNavLink href="#/orders">
                Orders
              </CNavLink>
              <CNavLink href="#/products" active>
                Products
              </CNavLink>
            </CNav>
          </CCardBody>
        </CCard>
        <CCard>
          <CCardBody>
            <p style={{fontSize: 25}}>
              Products
            </p>
            <CCol className='mb-2' style={{display:'flex', justifyContent:'right'}}>
              <CButton color={'primary'} onClick={() => setVisible(true)}>
                Create Product
              </CButton>
            </CCol>
            
            <CTable striped>
              <CTableHead>
                <CTableRow>
                  <CTableHeaderCell scope="col">N°</CTableHeaderCell>
                  <CTableHeaderCell scope="col">Name</CTableHeaderCell>
                  <CTableHeaderCell scope="col">Category</CTableHeaderCell>
                  <CTableHeaderCell scope="col">Price</CTableHeaderCell>
                  <CTableHeaderCell scope="col">Status</CTableHeaderCell>
                  <CTableHeaderCell scope="col">Actions</CTableHeaderCell>
                </CTableRow>
              </CTableHead>
              <CTableBody>
                { arrProducts.map (product => (
                  <CTableRow key={product.idProduct}>
                    <CTableDataCell>{product.idProduct}</CTableDataCell>
                    <CTableDataCell>{product.name}</CTableDataCell>
                    <CTableDataCell>{product.category}</CTableDataCell>
                    <CTableDataCell>$ {product.unitPrice}</CTableDataCell>
                    <CTableDataCell>{product.active ? 'Active' : 'Inactive'}</CTableDataCell>
                    <CTableDataCell>
                      <CButton color={'secondary'} onClick={() => onSelectedProduct(product, 'Edit')}>
                        Edit
                      </CButton>
                      {' '}
                      <CButton color={'danger'} onClick={() => onSelectedProduct(product, 'Delete')}>
                        Delete
                      </CButton>
                    </CTableDataCell>
                  </CTableRow>
                ))}
              </CTableBody>
            </CTable>
            
            {/* Add Modal */}
            <CModal alignment="center" visible={visible} onClose={() => setVisible(false)}>
              <CModalHeader>
                <CModalTitle>Add Product</CModalTitle>
              </CModalHeader>
              <CModalBody>
                <CFormFloating className="mb-3">
                  <CFormInput type="name" id="floatingName" name='name' onChange={handleChange}/>
                  <CFormLabel htmlFor="floatingCode">Name</CFormLabel>
                </CFormFloating>
                <CFormFloating className="mb-3">
                  <CFormInput type="category" id="floatingCategory" name='category' onChange={handleChange}/>
                  <CFormLabel htmlFor="floatingName">Category</CFormLabel>
                </CFormFloating>
                <CFormFloating className="mb-3">
                  <CFormInput type="unitPrice" id="floatingUnitPrice" name='unitPrice' onChange={handleChange}/>
                  <CFormLabel htmlFor="floatingDescription">Unit Price</CFormLabel>
                </CFormFloating>
              </CModalBody>
              <CModalFooter>
                <CButton color="success" onClick={() => pPost()}>
                  Confirm
                </CButton>
                <CButton color="secondary" onClick={() => setVisible(false)}>
                  Cancel
                </CButton>
              </CModalFooter>
            </CModal>
            { exito && 
              <CCol sm='4'>
                <CAlert color="success" dismissible>Se ha agregado el artículo correctamente.</CAlert>
              </CCol>}
            
            {/* Modal de editar */}
            <CModal alignment="center" visible={visibleEditar} onClose={() => setVisibleEditar(false)}>
              <CModalHeader>
                <CModalTitle>Editar Artículo</CModalTitle>
              </CModalHeader>
              <CModalBody>
                <CFormFloating className="mb-3">
                  <CFormInput type="code" id="floatingName" name='name' onChange={handleChange} value={newProduct && newProduct.name}/>
                  <CFormLabel htmlFor="floatingName">Name</CFormLabel>
                </CFormFloating>
                <CFormFloating className="mb-3">
                  <CFormInput type="name" id="floatingCategory" name='category' onChange={handleChange} value={newProduct && newProduct.category}/>
                  <CFormLabel htmlFor="floatingCategory">Category</CFormLabel>
                </CFormFloating>
                <CFormFloating className="mb-3">
                  <CFormInput type="description" id="floatingUnitPrice" name='unitPrice' onChange={handleChange} value={newProduct && newProduct.unitPrice}/>
                  <CFormLabel htmlFor="floatingUnitPrice">Unit Price</CFormLabel>
                </CFormFloating>
              </CModalBody>
              <CModalFooter>
                <CButton color="success" onClick={() => pPut()}>
                  Confirm
                </CButton>
                <CButton color="secondary" onClick={() => setVisibleEditar(false)}>
                  Cancel
                </CButton>
              </CModalFooter>
            </CModal>
            { exitoEditar && 
              <CCol sm='4'>
                <CAlert  color="success" dismissible>Se ha editado el artículo correctamente.</CAlert>
              </CCol>}

              {/* Modal de eliminar */}
            <CModal alignment="center" visible={visibleEliminar} onClose={() => setVisibleEliminar(false)}>
              <CModalHeader>
                <CModalTitle>Eliminar Artículo</CModalTitle>
              </CModalHeader>
              <CModalBody>
                ¿Está seguro de querer eliminar el artículo {newProduct && newProduct.nombre}?
              </CModalBody>
              <CModalFooter>
                <CButton color="danger" onClick={() => pDelete()}>
                  Confirm
                </CButton>
                <CButton color="secondary" onClick={() => setVisibleEliminar(false)}>
                  Cancel
                </CButton>
              </CModalFooter>
            </CModal>
            { exitoEliminar && 
              <CCol sm='4'>
                <CAlert  color="success" dismissible>Se ha eliminado el artículo correctamente.</CAlert>
              </CCol>}
          </CCardBody>
        </CCard>
      </CCol>
    </CRow>
  )
}

export default Products